# Generated by Django 5.0.4 on 2024-04-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='account_api.userprofile')),
                ('referring_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='account_api.userprofile')),
            ],
        ),
    ]
